School 18
llVeraVerall/MyReactPj pull request #9
Opened 2021-12-02 20:21 UTC by llVeraVerall

2021-12-03 07:15 UTC, gpont commented
Линтинг упал в CI, обрати внимание

2021-12-03 07:21 UTC, gpont requested changes

2021-12-03 07:21 UTC, gpont commented on src/App.tsx
> +    const token = localStorage.getItem('token');
Стоит завернуть эти строчки с инициализацией токена в useEffect(с пустыми зависимостями), чтобы не было реинита при ререндере

2021-12-03 07:21 UTC, gpont commented on src/api/fetchAddId1.ts
> +export const fetchList = () => fetch('https://ruprogrammer.ru/api/RestfullTest/',
Функция неправильно названа

2021-12-03 07:21 UTC, gpont commented on src/api/fetchDeleteEl.ts
> +export const fetchList = () => fetch('https://ruprogrammer.ru/api/RestfullTest/1',
Функция неправильно названа

2021-12-03 07:21 UTC, gpont commented on src/api/fetchAddId1.ts
> +            Id: 1,
Я так полагаю, id надо передавать через аргументы функции

2021-12-03 07:21 UTC, gpont commented on src/api/fetchUpdate.ts
> +export const fetchList = () => fetch('https://ruprogrammer.ru/api/RestfullTest/',
Функция неправильно названа

2021-12-03 07:21 UTC, gpont commented on src/hooks/errorSignIn.tsx
> +export const errorSignIn = (apiMethod: (...args: string[]) => Promise<unknown>, successMessage: string) => {
Дублирование кода. Уже есть хук useApi, можно юзать его вместо нового

2021-12-04 10:49 UTC, gpont requested changes

2021-12-04 10:49 UTC, gpont commented on src/App.tsx
> +    });
Лучше явно передать пустой список зависимостей useEffect, то есть:
```
useEffect() => {
  ...
}, []);
```

2021-12-04 10:49 UTC, gpont commented on src/api/fetchAddId1.ts
> +export const fetchAddId1 = ( id: number ) => fetch('https://ruprogrammer.ru/api/RestfullTest/',
А в сам запрос id не передается?

2021-12-04 10:49 UTC, gpont commented on src/hooks/errorSignIn.tsx
> +export const errorSignIn = (apiMethod: (...args: string[]) => Promise<unknown>, successMessage: string) => {
Если функция нигде не используется, то ее стоит удалить

2021-12-04 10:49 UTC, gpont commented on src/pages/SignIn/SignIn.tsx
> +            if (!/.+@.+\..+/.test(email)) {
Советую создать в src папку src/validators (в нее можно выносить валидаторы для разных полей форм), в которой создать файл `validateEmail.ts` с функцией
```
export const validateEmail = (email: string) => /.+@.+\..+/.test(email);
```

Так же можно поcтупить и со сравнением паролей в форме регистрации

2021-12-04 10:49 UTC, gpont commented on src/pages/Tasks/Tasks.tsx
> +        .then()
Список тут загружается, но не сохраняется в стор. То есть надо бы делать
```
.then((result) => result.json())
.then((list) => dispatch(addList(list)))
```

Ну и в компоненте тогда можно сразу отображать список, то есть:
```
const list = useSelector((state) => state.listEl.list));

...


<ul>
  {list.map((item) => (
    <li>{item}</li>
  )}
</ul>
```

2021-12-04 10:49 UTC, gpont commented on src/store/reducers/index.ts
> +    token, listEl, getId, addId1, updateEl, deleteEl
Список у нас один, а каждый редьюсер формирует свое место в сторе. То есть тебе надо объеденить все редьюсеры, связанные со списком в один

2021-12-04 10:49 UTC, gpont commented on src/store/reducers/deleteEl.ts
> +            list: action.payload
Экшен называется `DELETE_LIST`, но тут список не удаляется из стора

2021-12-04 10:49 UTC, gpont commented on src/store/reducers/addId1.ts
> +            list: action.payload
Экшена называется `ADD_ID1`, но список весь перезаписывается одним элементом

2021-12-04 10:56 UTC, gpont requested changes

2021-12-04 10:56 UTC, gpont commented on src/api/fetchDeleteEl.ts
> +export const fetchDeleteEl = () => fetch('https://ruprogrammer.ru/api/RestfullTest/1',
В url передается id удаляемого элемента списка, а он у тебя почему-то всегда `1`

2021-12-04 10:56 UTC, gpont commented on src/api/fetchGetId.ts
> +export const fetchGetId = () => fetch('https://ruprogrammer.ru/api/RestfullTest/1',
В url передается id удаляемого элемента списка, а он у тебя почему-то всегда `1`

2021-12-04 10:56 UTC, gpont commented on src/api/fetchUpdate.ts
> +export const fetchUpdate = (id: number) => fetch('https://ruprogrammer.ru/api/RestfullTest/',
А зачем нужен этот аргумент?

2021-12-05 21:16 UTC, gpont requested changes

2021-12-05 21:16 UTC, gpont commented on src/store/reducers/listEl.ts
> +    case 'ADD_TOKEN':
Токен в отдельном редьюсере. Чтобы он хранился не в `state.list.token`, а в `state.token`

2021-12-05 21:17 UTC, gpont commented
Ошибки тайпскрипта, надо бы пофиксить, посмотри в actions

2021-12-05 21:20 UTC, gpont requested changes

2021-12-05 21:20 UTC, gpont commented on src/pages/Tasks/Tasks.tsx
> +    // @ts-ignore
Стейт теперь затипизирован, так что можно убрать ts-ignore и eslint-ignore

2021-12-05 21:20 UTC, gpont commented on src/store/reducers/index.ts
> +    token, listEl, getId, addIdEl, updateEl, deleteEl
Убери удаленные редьюсеры

2021-12-06 21:51 UTC, llVeraVerall commented on src/api/fetchDeleteEl.ts
> +export const fetchDeleteEl = () => fetch('https://ruprogrammer.ru/api/RestfullTest/1',
потому что в задании такая ссылка была. На конце 1

2021-12-07 12:38 UTC, gpont commented on src/api/fetchDeleteEl.ts
> +export const fetchDeleteEl = () => fetch('https://ruprogrammer.ru/api/RestfullTest/1',
Так имеется в виду, что id удаляемого элемента передается в url

2021-12-10 17:24 UTC, closed without merging